<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="<?php echo $paths['CSS_PATH']; ?>style.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <div class="section">
    <div class="head"><h1>Student Voting System</h1></div>
    <div class="dash"><a href="index.php?page=dashboard">Go to dashboard</a></div>
    <div class="vote"><a href="index.php?page=vote">Vote</a></div>
</div>
</body>
</html>